import { animatedUno } from 'animated-unocss'
import {
  presetAttributify,
  presetIcons,
  presetMini,
  presetTypography,
  presetUno,
  presetWind,
} from 'unocss'
import presetAnimations from 'unocss-preset-animations'
import { presetRadix } from 'unocss-preset-radix'

export const presets = [
  presetUno(),
  presetMini(),
  presetWind(),
  presetAttributify(),
  presetIcons(),
  presetTypography(),
  animatedUno(),
  presetRadix({
    darkSelector: ':root',
    lightSelector: '.light',
    palette: [
      'gray',
      'mauve',
      'slate',
      'sage',
      'olive',
      'sand',
      'gold',
      'bronze',
      'brown',
      'yellow',
      'amber',
      'orange',
      'tomato',
      'red',
      'ruby',
      'crimson',
      'pink',
      'plum',
      'purple',
      'violet',
      'iris',
      'indigo',
      'blue',
      'cyan',
      'teal',
      'jade',
      'green',
      'grass',
      'lime',
      'mint',
      'sky',
      'black',
      'white',
    ],
  }),
  presetAnimations(),
]
